# the type of machine to run tests
dist: xenial
sudo: true
language: python

# which versions of python to test
python:
  - 3.6
  - 3.7
  - 3.8

# install the nii-masker package
install:
  - pip install .[test]

# run pytest
script:
  - pytest